coordinates     ../structure_2.pdb
structure       ../structure_2.psf
paraTypeCharmm  on
parameters      ../parameters/par_all27_prot_lipid_na.inp
parameters      ../parameters/probe.prm
parameters      ../parameters/cgenff.prm
parameters      ../parameters/par_all36m_prot.prm
outputname      min
restartname     min_restart
binaryoutput    no
restartfreq     1000
dcdfreq         1000
xstFreq         1000
outputEnergies  1000
outputPressure  1000
timestep        1.0
cutoff          10.0
switching       on
switchdist      8.0
pairlistdist    12.0
margin          1.0
exclude         scaled1-4
temperature     0
seed            12345
constraints     on
consref         ../structure_2.pdb
conskfile       ../structure_2.pdb
conskcol        B
constraintScaling  1.0
cellBasisVector1 	96.40 		0 		0 
cellBasisVector2 	0 		87.96 		0 
cellBasisVector3 	0 		0 		86.48 
cellOrigin 			43.78 	43.48 	43.24 
PME             yes
PMEGridSizeX        100
PMEGridSizeY        90
PMEGridSizeZ        90
wrapWater       on
wrapAll         on
minimize        10000
