coordinates     eq3.coor
structure       ../structure_5.psf
paraTypeCharmm  on
parameters      ../parameters/par_all27_prot_lipid_na.inp
parameters      ../parameters/probe.prm
parameters      ../parameters/cgenff.prm
parameters      ../parameters/par_all36m_prot.prm
outputname      sim
restartname     sim_restart
DCDfile         sim.dcd
binaryoutput    no
restartfreq     10000
dcdfreq         10000
xstFreq         10000
outputEnergies  50000
outputPressure  50000
outputtiming  10000
timestep        2.0
fullElectFrequency 2
nonbondedFreq      1
rigidBonds      all
cutoff          10.0
switching       on
switchdist      8.0
pairlistdist    12.0
margin          1.0
exclude         scaled1-4
wrapWater       on
wrapAll         on
velocities      eq3.vel
seed            352207
PME             yes
PMEGridSpacing  1.0
langevin         on
langevinDamping  5
langevinHydrogen off
useGroupPressure      yes
langevinPiston        on
langevinPistonTarget  1.01325
langevinPistonPeriod  100.0
langevinPistonDecay   50.0
langevinTemp     300
langevinPistonTemp    300
extendedSystem  eq3.xsc
run                  200000000
